services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    image: fastapi_app
    environment:
      - DATABASE_URL=postgresql://postgres:936042180S@db:5432/mydatabase

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: kwenda
      POSTGRES_PASSWORD: 936042180S
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
